apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-idwall
  name: desafio-devops-deployment
  namespace: desafio-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-idwall
  template:
    metadata:
      labels:
        app: deployment-idwall
    spec:
      containers:
      - name: aplication-idwall
        image: "pereirafmauro/desafio-devops:latest"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
